import braintree
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from orders.models import Order

# instantiate Braintree payment gateway
gateway = braintree.BraintreeGateway(settings.BRAINTREE_CONF)


def payment_process(request):
    order_id = request.session.get(
        "order_id"
    )  # get order_id which was stored in order_create view
    order = get_object_or_404(
        Order, id=order_id
    )  # retrieve the Order object for the given ID / 404
    total_cost = order.get_total_cost()

    if request.method == "POST":  # when view loaded with a POST request
        # retrieve nonce
        nonce = request.POST.get(
            "payment_method_nonce", None
        )  # nonce is generated by BrainTree
        # create and submit transaction
        result = gateway.transaction.sale(
            {
                "amount": f"{total_cost:.2f}",
                "payment_method_nonce": nonce,
                "options": {
                    "submit_for_settlement": True  # automatically submitted for settlement
                },
            }
        )

        if result.is_success:
            # mark the order as paid
            order.paid = True
            # store the unique transaction id
            order.braintree_id = result.transaction.id
            order.save()
            return redirect("payment:done")

        else:
            return redirect("payment:canceled")

    else:
        # generate token
        client_token = gateway.client_token.generate()

        return render(
            request,
            "payment/process.html",
            {"order": order, "client_token": client_token},
        )


def payment_done(request):
    return render(request, "payment/done.html")


def payment_canceled(request):
    return render(request, "payment/canceled.html")
